spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local

#  session:
#    store-type: jdbc
#    jdbc.initialize-schema: always

  datasource:
    url: jdbc:h2:tcp://localhost/~/bookshop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #create update none
    properties:
      hibernate:
        default_batch_fetch_size: 100
        #show-sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

#cloud:
#  aws:
#    s3:
#      bucket: blog-static-files1
#    credentials:
#      access-key: AKIA5FTZDUTZKRK745LL
#      secret-key: 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
#    region:
#      static: ap-northeast-2
#      auto: false
#    stack:
#      auto: false

logging.level:
  org.hibernate.SQL: debug

file:
  dir:
    item-image: C:\Users\voslr\study\files\bookShopFile\item-image
    main-image: C:\Users\voslr\study\files\bookShopFile\main-image


server:
  port: 9090